2012-12-07 14:40:12 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 8]
2012-12-07 14:40:12 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:00:03 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 10]
2012-12-07 15:00:03 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:02:02 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 10]
2012-12-07 15:02:02 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:21 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:21 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:32 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:32 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:33 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:33 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:34 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:34 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:34 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:34 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:34 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:34 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:34 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:34 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:35 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:35 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:35 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:35 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:35 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:35 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:35 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:35 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:03:36 Error: Fatal Error (1): Class 'navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:03:36 Error: [FatalErrorException] Class 'navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:07:56 Error: Fatal Error (1): Call to a member function query() on a non-object in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:07:56 Error: [FatalErrorException] Call to a member function query() on a non-object
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:08:26 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:08:26 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:09:03 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:09:03 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:10:30 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:10:30 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:10:31 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:10:31 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:14:09 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:14:09 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:15:33 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:15:33 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:15:36 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:15:36 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:15:37 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:15:37 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:17:09 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:17:09 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:17:44 Error: Fatal Error (1): Call to a member function getElements() on a non-object in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:17:44 Error: [FatalErrorException] Call to a member function getElements() on a non-object
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:21:22 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:21:22 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:22:23 Error: Fatal Error (1): Class 'Navigation' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:22:23 Error: [FatalErrorException] Class 'Navigation' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Navigati...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:23:22 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:23:22 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:23:40 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:23:40 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:24:29 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\cakephp\app\Controller\TestController.php, line 11]
2012-12-07 15:24:29 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:45:06 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:45:06 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:45:22 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:45:22 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:45:23 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:45:23 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:45:23 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:45:23 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:45:23 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:45:23 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:45:24 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:45:24 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:45:48 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:45:48 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:45:49 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:45:49 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:46:46 Error: Fatal Error (1): Class 'Test' not found in [C:\xampp\htdocs\t3con\app\Controller\TestController.php, line 10]
2012-12-07 15:46:46 Error: [FatalErrorException] Class 'Test' not found
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Class 'Test' no...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:48:05 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\t3con\app\Model\Test.php, line 14]
2012-12-07 15:48:05 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:50:00 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\t3con\app\Model\Test.php, line 14]
2012-12-07 15:50:00 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:50:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\t3con\app\Model\Test.php, line 14]
2012-12-07 15:50:33 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:50:36 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\t3con\app\Model\Test.php, line 14]
2012-12-07 15:50:36 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:50:48 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\t3con\app\Model\Test.php, line 14]
2012-12-07 15:50:48 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:50:50 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\t3con\app\Model\Test.php, line 14]
2012-12-07 15:50:50 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:51:11 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\t3con\app\Model\Test.php, line 14]
2012-12-07 15:51:11 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-07 15:51:43 Error: Fatal Error (1): Call to undefined function find() in [C:\xampp\htdocs\t3con\app\Model\Test.php, line 14]
2012-12-07 15:51:43 Error: [FatalErrorException] Call to undefined function find()
#0 C:\xampp\htdocs\t3con\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\t3con\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
